### ISSUE TITLE
Задание 2

### ISSUE THREAD

**Issue by ala-n** [aadereiko/up#2]
Агонь :D 👍 

Но теперь детали:
- О том что за контроллы при добавлении поста пока можно только догадываться... (По виду это так называемый material но тогда к примеру, неактивные инпуты должны иметь нижнею линию и плейсхолдер (текст описывающий что это)) 
PS: Если твои моки предполагают что все должно быть сделано именно в таком дизайне, то не обязательно прям детально описывать то, что уже придумано, можно написать коммент:
"input control like this https://material.angular.io/components/input/overview". 
- Аналогично фильтры: можно указать что за контрол и где он будет и этого будет достаточно. Моки это не столько дизайн сколько прототип/описание того как примерно выглядит и самое главное действует приложение (хороший мок может состоять вообще только из расположения элементов и комментариев ).
- Еще из той же оперы: я вижу значек фильтра но о том что это кнопка или просто значек ни слова)
- Итого комментарии, пожалуйста) (не много, но если ты в моке сразу фиксируешь что именно за контрол, то комментарий должен быть, иначе мало кто догадется а что же именно тут предполагается)
- Вижу дизайн для мобилы, но не совсем понятно как все будет на десктопе. (хотя бы главную страничку, на дублировании всего не настаиваю, будем считать что мобильно ориентированный мок сайта будет)  
- **Детали касательно ТЗ**:
-- в целом кстати многое замечено что другие не сразу сделали, но это самый важный пункт в этом задании поэтому внимательно.
-- задание на 9-10 (я не на что не намекаю, но у тебя прям наводка как его за 5 минут можно было сделать ) 
--  детали вроде "После нажатия на кнопку
удаления поста пользователь должен подтвердить, что он хочет удалить фото пост."@ТЗ также важны

- Pull request по готовности

**Comment by djadjka** [comment]
1)Футер, на странице авторизации он ок, дальше он вообще не ок 
2)Подлизываться не хорошо 
3)-1 балл за то что не самая удачная моя фоточка 
=)

**Comment by ala-n** [comment]
+https://github.com/aadereiko/up/commit/803187c7b5a60dbacc0c2ab0ebd61ed436eebb43

**Comment by ala-n** [comment]
Например файл "mockups/add/AddPotss.png" : 
- Не учтено замечание по поводу полей ввода:
На моках в первую очередь должны быть обозначены контроллы (их области) и уже опционально как я писал можно указать как именно они выглядят. В задании 9/10 в частности сказано сделать так с хэштегами (детально описать что это и как выглядит). (Еще раз: мокап != дизайнерский прототип. Может включать в себя, но в прервую очередь должен ОПИСЫВАТЬ интерфейс не упуская детали ТЗ)
- Зачем по 2 файла к скрину? контрастним мерким шрифтом пометки при необходимости со стрелочками и все будет видно
- (9/10) Контрол хэштегов не описан: я вижу текст и 3 кнопки но как они будут действовать остается только догадываться: вот нажму я на кнопку edit а дальше? "поле с хэштегами превращается в текстовое поле с автоподсказкой" ? - даже если это так то это это я написал и это остается догадкой пока явно не указано/зарисовано/прописано.
PS: детали сложных контролов как этот можно выносить в отдельный скрин, т.е. например условно:
на основных скринах все как есть только контрол с меткой "hashtag-editor", а в hashtag-editor.png нарисован этот контрол во всех позах )

Работа в целом визуально очень хороша, очень жду оствашихся правок в течении недели.
Если будет попрвленно на идеально (+ хотябы главная страница в варианте для десктопа)  то будет 10 (-0.5 за не в срок но +0.5 за perfect)

**Comment by aadereiko** [comment]
Напоминаю про посмотреть мокапы.

**Comment by ala-n** [comment]
Супер что напомнил. Глянул.
